version: 2.1

orbs:
  rn: react-native-community/react-native@7.4.0

jobs:
  checkout_code:
    executor:
      name: rn/linux_js
      node_version: '20.11'
    steps:
      - checkout
      - run:
          command: yarn install
      - persist_to_workspace:
          root: .
          paths: .
  analyse:
    executor:
      name: rn/linux_js
      node_version: '20.11'
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Lint JS Code (ESLint)
          command: yarn run lint
      - run:
          name: Jest
          command: yarn run test

workflows:
  test:
    jobs:
      - checkout_code
      - analyse:
          requires:
            - checkout_code
      - rn/android_build:
          name: build_android_debug
          project_path: "example/android"
          build_type: debug
          requires:
            - analyse
          build_image_version: 'latest'
          java_options: '-Xmx3584m -XX:+UnlockExperimentalVMOptions -XX:+UseContainerSupport'
          resource_class: large
      - rn/android_build:
          name: build_android_release
          project_path: "example/android"
          build_type: release
          requires:
            - analyse
          build_image_version: 'latest'
          java_options: '-Xmx3584m -XX:+UnlockExperimentalVMOptions -XX:+UseContainerSupport'
          # The resource_class feature allows configuring CPU and RAM resources for each job. Different resource classes are available for different executors. https://circleci.com/docs/2.0/configuration-reference/#resourceclass
          resource_class: large

#      - rn/android_test:
#          detox_configuration: "android.emu.release"
#          detox_loglevel: "trace"
#          requires:
#            - build_android_release
