version: 2.1

orbs:
  rn: react-native-community/react-native@8.0.0

jobs:
  checkout_code:
    executor:
      name: rn/linux_js
      node_version: '20.11'
    steps:
      - checkout
      - run:
          command: yarn install
      - persist_to_workspace:
          root: .
          paths: .
  analyse:
    executor:
      name: rn/linux_js
      node_version: '20.11'
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Lint JS Code (ESLint)
          command: yarn run lint
      - run:
          name: Jest
          command: yarn run test
  build_android:
    executor:
      name: rn/linux_android
      build_image_version: 'latest'
      resource_class: large
    steps:
      - attach_workspace:
          at: .
      - run:
          name: build
          command: |
            yarn example build:android
            yarn example test:android:build

workflows:
  test:
    jobs:
      - checkout_code
      - analyse:
          requires:
            - checkout_code
      - build_android:
          name: build_android
          requires:
            - analyse