name: "Build and Test"

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  analyse:
    name: Analyse
    runs-on: macos-13

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup
        uses: ./.github/actions/setup

      - name: Test
        run: yarn ci

  build-android:
    name: Build Android
    needs: analyse
    runs-on: macos-13

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup
        uses: ./.github/actions/setup

      - name: Setup java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: '19'

      - name: Restore cache gradle cache
        id: cache-gradle-cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/wrapper
            ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ secrets.CACHE_VERSION }}-${{ hashFiles('**/gradle-wrapper.properties') }}-${{ hashFiles('**/build.gradle') }}-${{ hashFiles('**/settings.gradle') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Downloading Gradle Dependencies
        if: steps.cache-gradle-cache.outputs.cache-hit != 'true'
        run: |
          cd example/android
          chmod +x gradlew
          ./gradlew --max-workers 2 downloadDependencies

      - name: Build Android Release
        run: |
          cd example
          yarn detox build -c android.emu.release

      - name: Test Android Release
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          avd-name: TestingAVD
          script: cd example && yarn detox test -c android.emu.release -l info --headless

  build-ios:
    name: Build iOS
    needs: analyse
    runs-on: macos-13

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup
        uses: ./.github/actions/setup

      - name: setup-cocoapods
        uses: maxim-lobanov/setup-cocoapods@v1
        with:
          podfile-path: example/ios/Podfile.lock

      - name: Restore cache Pods
        id: cache-pods
        uses: actions/cache@v4
        with:
          path: |
            **/vender/bundle
            **/ios/Pods
          key: ${{ runner.os }}-cocoapods-${{ hashFiles('**/Podfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-cocoapods-

      - name: Install CocoaPods
        run: |
          cd example
          bundle install
          yarn pod-install
        env:
          RCT_NEW_ARCH_ENABLED: 1

      - name: Install CocoaPods
        run: |
          cd example/ios
          bundle exec pod install
        env:
          RCT_NEW_ARCH_ENABLED: 1

      - name: Install Detox dependencies
        run: |
          cd example
          brew tap wix/brew
          brew install applesimutils
          yarn detox clean-framework-cache
          yarn detox build-framework-cache

      - name: Xcode Version
        run: |
          xcodebuild -version
          xcrun simctl list

      - name: Build iOS Release
        run: |
          cd example
          yarn detox build -c ios.sim.release

      - name: Test iOS Release
        run: |
          cd example
          yarn detox test -c ios.sim.release -l info -u --headless